### ISSUE TITLE
contactIntensity definitions

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-episim#48]
Previously, I saw that the `contactIntensity` for public transport vehicles was set to `10` but this now appears to default to `1` across all modes and activities.

From recent blogs [here](https://covid-sim.info/v9/masks/berlin) I see that for your Berlin example that:
`Contact intensity was set to 1 for home activities (was 3 before)`

Can you comment or advise on your practical experience with this parameter? It makes some sense to increase the `contactIntensity` for certain dense modes (e.g underground lines) but I wonder how this relates to the assumptions/models/data that epidemiological models traditionally hold. Do you take these values as assumptions, or use them in calibration?

I have done some sensitivity analysis with this parameter and it is obviously highly sensitive and can influence the wider dynamics significantly.

**Comment by rakow** [comment]
In our most recent model we estimate the contact intensity with:
   
  ci = 1 / (typicalFloorSpacePerPerson * airExchangeRate)

Since the early beginning we switched to a more "aerosol-like" contact model, meaning that the room size and amount of fresh air are the most important factors.

You can see the concrete values we are using here:

https://github.com/matsim-org/matsim-episim/blob/9617a2b5b53356566c43687f2351f88af2f1dbd7/src/main/java/org/matsim/run/modules/SnzBerlinWeekScenario2020.java#L196-L201

For PT vehicle we can identify the type and estimate the sizes of the cabins quite reliably. Of course, we have to make certain assumptions about how well a vehicle is ventilated.

We are currently also in the process of writing this up and updating our pre-print.  So we should be able to give you more details on that soon.

**Comment by rakow** [comment]
Here is the updated prepint containing more information regarding the infection model: https://arxiv.org/abs/2011.11453
Please open a new issue if there are further questions.
